version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    working_directory: ~/book
    branches:
      only: deploy_book
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "14:6e:89:32:9d:8a:9f:a5:d5:3a:b2:0c:87:bb:ae:54"
      - deploy:
          name: deploy to product
          command: |
            if [ "${CIRCLE_BRANCH}" == "deploy_book"  ]; then
              scp -oStrictHostKeyChecking=no -r [!.]* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}
            fi
